### ISSUE TITLE
Fails to compile with current nightly

### ISSUE THREAD

**Issue by dignifiedquire** [bodil/typed-html#112]
- `rustc --version rustc 1.44.0-nightly (94d346360 2020-04-09)`

Likely a bug in the nightly compiler, but maybe already known here? All working fine on `1.42`.

```
   Compiling typed-html v0.2.2 (/Users/dignifiedquire/opensource/typed-html/typed-html)
error: overflow representing the type `std::option::Option<&T>`

error: aborting due to previous error

error: overflow representing the type `std::option::Option<&T>`

error: aborting due to previous error

error: could not compile `typed-html`.
```

**Comment by chrysn** [comment]
I'm reported this as a Rust error at https://github.com/rust-lang/rust/issues/71359.

The current workaround (and possibly acceptable solution to be applied here) is to increase the recursion limit of typed-html to 130 (or 256 right away).

**Comment by chrysn** [comment]
The vec reimplementation of the offending Event interator (in #117) appears to achieve the same; applying either makes things buildable in nightly.

**Comment by bodil** [comment]
I went with #117, which should scale better.
