### ISSUE TITLE
[Feature request]: Split out typed html part from platform part

### ISSUE THREAD

**Issue by derekdreery** [bodil/typed-html#17]
I'd like to use this library, but I can't as I use wasm-bindgen. It would be great if we could split out the client-side code into a separate feature/crate.

The difficulty is complex data, especially function callbacks on event handlers. An approach to this problem is to use generics, like how elm does it:

```elm
fancyInput : String -> String -> String -> Html inputMsg
fancyInput idVal name value =
  div []
    [ label [ for
    , input 
      [ id idVal
      , onInput inputMsg
      ] 
      [ text value ]
    ]
```

The important thing here is that we pass in a generic type (`inputMsg`) we want to be returned when there is input. This should be a type constructor that takes a string (the new value). This means there are no callbacks - there is just a value that changes type as it moves up through the tree, and then at the top we will explain the consequences using a function like

```elm
update : msg -> model -> model
```

where we explain how this message changes our model. There may also be side-effects like web activity.

I'm not sure if this is possible in rust, but a model like this is completely independent of backend - on the server for example all the event handlers just do nothing.

**Comment by bodil** [comment]
I'm aware of this problem, and I think I know how to fix it - hoping to have it ready before I tag the next release.

**Comment by derekdreery** [comment]
Ping me if you want any help.
