### ISSUE TITLE
Tree Diffing

### ISSUE THREAD

**Issue by sdobz** [bodil/typed-html#24]
The name of this project seems scoped to macro->VTree, do you plan on including diffing and patching?

If so the https://github.com/Matt-Esch/virtual-dom project provides a decent starting point for an API and tree diffing algorithm.

The implementation in this project would look something like:
* determine Patch type by comparing stdweb, web-sys, ?string?
* write diff<T: OutputType>(left: T, right: T) -> Iterator<Patch>
* write patch<T: OutputType>(e: OutputType::Element, p: Patch)
* write new outputs for string, stdweb, and web-sys

The virtual-dom reference should be sufficient that implementation isn't an issue and we only need to concern ourselves with types

**Comment by bodil** [comment]
No, that's out of scope for this crate. Its responsibility stops at providing all the information required for a differ implementation to do its work. It's likely I'll be writing a differ at some point (though I'd prefer if someone beat me to it) but it'll be a different crate if so.

**Comment by sdobz** [comment]
Excellent, thanks for your response. I'll be taking a crack at it, though as a novice I'm not sure how far I'll get.
