### ISSUE TITLE
Ignore CSS written between style tags?

### ISSUE THREAD

**Issue by nabeelomer** [bodil/typed-html#29]
The parser can ignore all the tokens that appear between <style> tags, that way CSS doesn't have to be written in external files all the time.

PS. Thank you for your awesome work!

**Comment by bodil** [comment]
I'm not sure the token stream will contain enough info to reconstruct a valid CSS document, but I can look into it. Of course, the better solution would be to have a similar DSL to typed-html for CSS...

**Comment by bodil** [comment]
Sorry, doesn't seem like it's possible without wrapping it in quotes.
