### ISSUE TITLE
Types taking `Uri` is too restrictive.

### ISSUE THREAD

**Issue by icefoxen** [bodil/typed-html#31]
Basically, various things like `a` tags take a [`Uri`](https://docs.rs/http/0.1.14/http/uri/struct.Uri.html) as arguments.  The URI defined there is intended for use in HTTP requests, which are always absolute.  However, in HTML, it is possible (and often extremely useful) to have relative URL's, which the `Uri` structure does not support.

If you have any suggestions for better structures to use, I'll happily make a PR for it.

**Comment by bodil** [comment]
Well, if there were a URI type already which accepted fragmentary URIs (as well as things like `javascript:` URIs) I'd leap at it, but I strongly suspect one has to be written first...

**Comment by bodil** [comment]
See also #30, btw.

**Comment by icefoxen** [comment]
Thanks.  I'll see if I can write one, but no promises that it'll be any good.  ;-)

**Comment by bodil** [comment]
That's a particularly hairy task, as I recall from having worked on similar code in prehistory. It might be smarter in the short term to just accept a `String`.

**Comment by bodil** [comment]
As there's currently no obvious alternative, I think the best course of action would be to just make `Uri` an alias to `String`. I'll be committing a fix to that effect straight away, no need for a PR.
