### ISSUE TITLE
Embedding HTML from a string into tree

### ISSUE THREAD

**Issue by LPGhatguy** [bodil/typed-html#34]
I'm porting one of my projects from a janky DSL I wrote to typed-html. It's going pretty well overall!

I'm trying to embed rendered Markdown content, which I use `pulldown_cmark` to generate, but I can't figure out how to embed the generated HTML without it getting escaped.

Is there a trick to doing this with the current API, or is this something that needs to be implemented still?

**Comment by bodil** [comment]
You'd need something like a wrapper type for `String` which renders without escaping, eg. `SafeString::new("I am a string")`. This isn't currently provided by typed-html, but should be an easy fix.

**Comment by ckampfe** [comment]
I have a patch for this that seems to be working locally. I should be able to push it up this week.

**Comment by lazypassion** [comment]
@ckampfe how did you embed the string of generated html into the html macro? Did you use the text macro?

**Comment by ckampfe** [comment]
@lazypassion correct. I parsed markdown to html (with another project), and attempted to embed that string in a `typed-html` template with the `text!` macro.

**Comment by bodil** [comment]
#39 should resolve this.
