### ISSUE TITLE
rustc nightly required to compile wasm example?

### ISSUE THREAD

**Issue by egeriis** [bodil/typed-html#6]
Is it the correct interpretation of below error message, that rustc nightly is required to compile the wasm example?

`$ cargo web build`

```
error[E0554]: #![feature] may not be used on the stable release channel
   --> /Users/ronni/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.10/src/lib.rs:115:5
    |
115 | /     feature(use_extern_macros)
116 | | )]
    | |_^
```

Edit: I noticed you removed the note in the main readme about requiring nightly

**Comment by dtolnay** [comment]
This is a bug in stdweb. If you patch in a version of stdweb with [these lines](https://github.com/koute/stdweb/blob/0.4.10/src/lib.rs#L113-L116) commented out, then it works on stable. The use_extern_macros feature was stabilized in Rust 1.30.

Tested by adding to Cargo.toml:

```toml
[patch.crates-io]
stdweb = { path = "../stdweb" }
```

and running:

```console
$ cargo +stable build --target wasm32-unknown-unknown
```

**Comment by egeriis** [comment]
I'm new to Rust, so I just need to make sure I understand you correctly. What you're saying is, put a copy of stdweb into `../stdweb`, then patch the file as you noted. Did I understand that correctly?

**Comment by dtolnay** [comment]
Yep, that would work!
