### ISSUE TITLE
Trying to use AsRef<str> with a template

### ISSUE THREAD

**Issue by xrl** [bodil/typed-html#84]
I want to make a function which takes a variety of string-y inputs. Think str/String/Vec<u8> (haven't tested that last one).

I was trying this function definition:

```
fn timestamp_table<'a, S: AsRef<str>>(
    now: &'a NaiveDateTime,
    rows: impl Iterator<Item = (S, NaiveDateTime)>,
) -> Box<typed_html::elements::table<String>> {
    html!(<table>
            <tr>
                <th>"Name"</th>
                <th>"Age"</th>
            </tr>
        {
            rows.map(|t| html!(
                <tr>
                    <td>{text!(t.0)}</td>
                    <td>{text!(elapsed(*now,t.1))}</td>
                </tr>
            ))
        }
        </table>)
}
```

and rustc errored with:

```
error[E0277]: the trait bound `std::string::String: std::convert::From<S>` is not satisfied
   --> src/pages/home.rs:155:5
    |
155 | /     html!(<table>
156 | |             <tr>
157 | |                 <th>"Name"</th>
158 | |                 <th>"Age"</th>
...   |
167 | |         }
168 | |         </table>)
    | |_________________^ the trait `std::convert::From<S>` is not implemented for `std::string::String`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<std::string::String>` for `S`
    = note: required by `typed_html::dom::TextNode::<T>::new`
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

My code doesn't talk about the `From` conversion trait so I assume there's some kind of issue that a `AsRef<str>` isn't compatible with `From`. Would it be better to do something in my code or is this a change that can be put in to this library?

FYI, AsRef is new to me, I found the technique on SO: https://stackoverflow.com/questions/55079070/how-to-accept-str-string-and-string-in-a-single-rust-function

**Comment by bodil** [comment]
Yeah, `VNode` needs a `String` to store and the macro will try to use `From` to get one. As far as I can tell without actually running it through rustc, there are `From` implementations for `&str`, `&String` etc, so you should be able to make the constraint `S: Into<String>` instead, which should have the same end result as the `AsRef<str>` would under different circumstances.

**Comment by xrl** [comment]
Awesome, that did it! Thank you so much!
