### ISSUE TITLE
project fails to build in release mode while consuming gigabytes of memory

### ISSUE THREAD

**Issue by iamcodemaker** [bodil/typed-html#96]
I'm trying to add `typed-html` support to a [web framework](https://github.com/iamcodemaker/euca) I built and am encountering an issue building a sample app. Everything works fine in debug mode, but release mode builds eat up gigabytes of memory. I'm not sure if this is a problem with `typed-html` or `rustc` but it doesn't happen when not using `typed-html`.

Code is [here](https://github.com/iamcodemaker/euca-counter). Run `wasm-pack build` or `cargo build --release` in the `crate.typed-html` directory to observe the issue. Building with `wasm-pack build --dev` or `cargo build` works fine.

**Comment by arendjr** [comment]
I am thinking of using `typed-html` for a hobby project, but seeing how it's currently unmaintained, this issue worried me... So I tried to create a release build with `rustc 1.43.1` using `cargo build --release`, but it works for me. It did consume quite a bit of CPU for a few seconds, but it worked alright...

**Comment by rofrol** [comment]
Use git version https://github.com/bodil/typed-html/pull/117#issuecomment-644859739

**Comment by iamcodemaker** [comment]
Confirmed, fixed by #117
